# PARTE 1

# Exercício 1 - Regressão (Appliances Energy Prediction)

# Carregamento dos dados

In [ ]:
import pandas as pd

df_energy = pd.read_csv('/content/energydata_complete.csv')
display(df_energy.head())
display(df_energy.info())

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

None

# Pré-processamento dos dados

In [ ]:
from sklearn.preprocessing import StandardScaler

df_energy = df_energy.drop('date', axis=1)

X = df_energy.drop(['Appliances', 'lights'], axis=1)
y = df_energy['Appliances']

continuous_features = X.columns.tolist()

scaler = StandardScaler()

X[continuous_features] = scaler.fit_transform(X[continuous_features])

display(X.head())
display(y.head())

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
0 -1.118645  1.843821 -0.520411  1.073683 -1.235063  1.686130 -0.908217   
1 -1.118645  1.616807 -0.520411  1.057097 -1.235063  1.704566 -0.908217   
2 -1.118645  1.517959 -0.520411  1.033550 -1.235063  1.748608 -0.944115   
3 -1.118645  1.459321 -0.520411  1.024540 -1.235063  1.769092 -0.962063   
4 -1.118645  1.526336 -0.520411  1.009797 -1.235063  1.769092 -0.962063   

       RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
0  1.506438 -1.314903  0.471160  ... -1.217324  0.958136 -0.152647   
1  1.604528 -1.314903  0.471160  ... -1.200778  0.965363 -0.174588   
2  1.580918 -1.314903  0.458968  ... -1.233869  0.950910 -0.196529   
3  1.542526 -1.314903  0.458968  ... -1.233869  0.926821 -0.218470   
4  1.497991 -1.296832  0.458968  ... -1.233869  0.926821 -0.240411   

   Press_mm_hg   RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0    -2.976328  0.82208   1.207694    2.091596   0.366975 -0.807974 -0.807974  
1    -2.962813  0.82208   1.071703    1.766584   0.343135 -0.440240 -0.440240  
2    -2.949298  0.82208   0.935713    1.441572   0.319294  0.252109  0.252109  
3    -2.935783  0.82208   0.799723    1.116559   0.295454  1.408801  1.408801  
4    -2.922268  0.82208   0.663733    0.791547   0.271613 -1.028122 -1.028122  

[5 rows x 26 columns]

0    60
1    60
2    50
3    50
4    60
Name: Appliances, dtype: int64

# Processamento dos dados

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
2133  -1.118645  1.316914 -0.520411  1.147399 -0.935970  1.550932 -0.859265   
19730  2.415962  1.583299  2.530318  0.394449  2.458745  0.590209  1.882026   
3288   0.506486  1.048015  0.543620  0.533104 -0.151679  1.632358  0.560332   
7730  -1.180910 -0.552810 -1.432438  0.126032 -0.831287 -0.638860 -1.206822   
8852  -0.676559 -1.248930 -1.478040 -0.154906 -0.985819 -0.689047 -0.663458   

           RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
2133   1.767501 -1.128170  0.227307  ... -1.151142  1.721736  0.543199   
19730  1.511812  1.955947  0.160801  ...  1.843571  1.261649  2.881489   
3288   0.331650 -0.266786  0.485200  ... -0.439691  0.958136 -0.152647   
7730  -0.466898 -0.705911 -0.963142  ... -0.543927 -0.199708 -0.998945   
8852  -1.042775 -0.754702 -0.216063  ... -0.277546 -0.352268 -1.556875   

       Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
2133      0.861898  0.385860   1.411679   -1.257445   0.998749  0.983207   
19730    -0.043599 -1.616282  -0.288198   -1.243314   2.282163  1.249203   
3288      0.632145 -1.057025   1.615664    0.141522  -0.848891  1.177312   
7730     -1.890633  0.978673  -1.240129    0.876332  -0.602539 -0.853473   
8852      1.722345  0.844451  -0.968148   -0.367193  -1.357488 -0.971982   

            rv2  
2133   0.983207  
19730  1.249203  
3288   1.177312  
7730  -0.853473  
8852  -0.971982  

[5 rows x 26 columns]

T1      RH_1        T2      RH_2        T3      RH_3        T4  \
8980  -0.495989 -1.221286 -1.177071 -0.308889 -0.985819 -0.719774 -0.536184   
2754   0.126666  3.226846  0.432657  1.213743 -0.316181  3.067809 -0.157625   
9132  -0.184662 -1.196155 -1.234832  0.026926 -0.299565 -1.242129 -0.276741   
14359 -0.184662  0.194410  1.618292 -1.371209 -0.116785 -0.709532  0.751244   
8875  -1.072983 -1.289977 -1.768368 -0.072181 -1.130381 -0.873408 -0.780942   

           RH_4        T5      RH_5  ...        T9      RH_9     T_out  \
8980  -1.111880 -0.537850  0.037766  ... -0.097202 -0.607604 -1.061634   
2754   0.446825 -1.037815  0.804181  ... -1.586286  0.637762 -0.886105   
9132  -1.213234  0.004279 -1.181502  ... -0.047565 -0.785857 -1.356271   
14359 -0.873237  0.022350 -0.851561  ...  0.399160 -0.720819  0.270502   
8875  -0.935278 -0.922763 -0.216063  ... -0.241146 -0.205329 -1.481649   

       Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
8980      1.807939  0.576007  -0.696168    2.091596  -0.896572  0.043748   
2754     -0.124689  0.687859  -0.424188   -0.960694  -0.610486 -0.104410   
9132      1.443037  0.218082  -0.832158    2.261168  -1.468744 -1.713867   
14359     1.659275 -0.598434   0.459748    0.141522  -0.010499 -1.013680   
8875      1.909301  0.911562  -0.016218    0.890463  -1.242259 -0.981899   

            rv2  
8980   0.043748  
2754  -0.104410  
9132  -1.713867  
14359 -1.013680  
8875  -0.981899  

[5 rows x 26 columns]

2133      50
19730    100
3288      70
7730      40
8852      40
Name: Appliances, dtype: int64

8980     40
2754     90
9132     50
14359    50
8875     70
Name: Appliances, dtype: int64

# Treinamento dos modelos de regressão

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

lr_model = LinearRegression()
dt_model = DecisionTreeRegressor(random_state=42)
rf_model = RandomForestRegressor(random_state=42)

lr_model.fit(X_train, y_train)
dt_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

# Avaliação  dos modelos

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

y_pred_lr = lr_model.predict(X_test)
y_pred_dt = dt_model.predict(X_test)
y_pred_rf = rf_model.predict(X_test)

rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)
mae_lr = mean_absolute_error(y_test, y_pred_lr)

rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
r2_dt = r2_score(y_test, y_pred_dt)
mae_dt = mean_absolute_error(y_test, y_pred_dt)

rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)

print("Model Evaluation Results:")
print("-" * 40)
print(f"{'Modelo':<20} | {'RMSE':<10} | {'R²':<10} | {'MAE':<10}")
print("-" * 40)
print(f"{'Regressão Linear':<20} | {rmse_lr:<10.4f} | {r2_lr:<10.4f} | {mae_lr:<10.4f}")
print(f"{'Regressão de Árvore de Decisão':<20} | {rmse_dt:<10.4f} | {r2_dt:<10.4f} | {mae_dt:<10.4f}")
print(f"{'Random Forest Regressor':<20} | {rmse_rf:<10.4f} | {r2_rf:<10.4f} | {mae_rf:<10.4f}")
print("-" * 40)

Model Evaluation Results:
----------------------------------------
Modelo               | RMSE       | R²         | MAE       
----------------------------------------
Regressão Linear     | 92.4523    | 0.1459     | 53.4392   
Regressão de Árvore de Decisão | 90.7799    | 0.1765     | 38.1252   
Random Forest Regressor | 64.0201    | 0.5904     | 30.5115   
----------------------------------------


# Compararação dos resultados

In [ ]:
print("Comparação de Desempenho dos Modelos:")
print("-" * 40)
print(f"{'Modelo':<20} | {'RMSE':<10} | {'R²':<10} | {'MAE':<10}")
print("-" * 40)
print(f"{'Regressão Linear':<20} | {rmse_lr:<10.4f} | {r2_lr:<10.4f} | {mae_lr:<10.4f}")
print(f"{'Regressão de Árvore de Decisão':<20} | {rmse_dt:<10.4f} | {r2_dt:<10.4f} | {mae_dt:<10.4f}")
print(f"{'Random Forest Regressor':<20} | {rmse_rf:<10.4f} | {r2_rf:<10.4f} | {mae_rf:<10.4f}")
print("-" * 40)

print("\nDiscussão:")
print("Para avaliar o desempenho dos modelos de regressão, utilizamos as seguintes métricas:")
print("- RMSE (Root Mean Squared Error): Mede a raiz quadrada da média dos erros quadrados. Penaliza erros maiores e indica a magnitude típica dos erros de previsão na mesma unidade da variável alvo.")
print("- R² (R-squared): Representa a proporção da variância na variável dependente que é previsível a partir das variáveis independentes. Um valor mais próximo de 1 indica que o modelo explica uma maior parte da variância dos dados.")
print("- MAE (Mean Absolute Error): Mede a média dos erros absolutos. É menos sensível a outliers que o RMSE e fornece uma ideia do erro médio absoluto das previsões.")

print("\nCom base nos resultados:")

best_model = ""
if rmse_rf < rmse_dt and rmse_rf < rmse_lr:
    best_model = "Random Forest Regressor"
elif rmse_dt < rmse_lr:
    best_model = "Regressão de Árvore de Decisão"
else:
    best_model = "Regressão Linear"

print(f"O modelo com o menor RMSE é o {best_model} ({min(rmse_lr, rmse_dt, rmse_rf):.4f}).")

best_r2_model = ""
if r2_rf > r2_dt and r2_rf > r2_lr:
    best_r2_model = "Random Forest Regressor"
elif r2_dt > r2_lr:
    best_r2_model = "Regressão de Árvore de Decisão"
else:
    best_r2_model = "Regressão Linear"

print(f"O modelo com o maior R² é o {best_r2_model} ({max(r2_lr, r2_dt, r2_rf):.4f}).")

best_mae_model = ""
if mae_rf < mae_dt and mae_rf < mae_lr:
    best_mae_model = "Random Forest Regressor"
elif mae_dt < mae_lr:
    best_mae_model = "Regressão de Árvore de Decisão"
else:
    best_mae_model = "Regressão Linear"

print(f"O modelo com o menor MAE é o {best_mae_model} ({min(mae_lr, mae_dt, mae_rf):.4f}).")


print("\nConclusão:")
if best_model == "Random Forest Regressor" and best_r2_model == "Random Forest Regressor" and best_mae_model == "Random Forest Regressor":
    print("Com base nas métricas de avaliação (RMSE, R² e MAE), o modelo Random Forest Regressor demonstrou o melhor desempenho na previsão do consumo de energia. Ele apresentou o menor erro médio de previsão (RMSE e MAE) e explicou a maior proporção da variância no consumo de energia (R²), indicando que é o modelo que melhor se ajusta aos dados e prevê o consumo de forma mais precisa.")
elif best_model == "Regressão Linear" and best_r2_model == "Regressão Linear" and best_mae_model == "Regressão Linear":
     print("Com base nas métricas de avaliação (RMSE, R² e MAE), o modelo de Regressão Linear demonstrou o melhor desempenho na previsão do consumo de energia. Ele apresentou o menor erro médio de previsão (RMSE e MAE) e explicou a maior proporção da variância no consumo de energia (R²), indicando que é o modelo que melhor se ajusta aos dados e prevê o consumo de forma mais precisa.")
elif best_model == "Regressão de Árvore de Decisão" and best_r2_model == "Regressão de Árvore de Decisão" and best_mae_model == "Regressão de Árvore de Decisão":
     print("Com base nas métricas de avaliação (RMSE, R² e MAE), o modelo de Regressão de Árvore de Decisão demonstrou o melhor desempenho na previsão do consumo de energia. Ele apresentou o menor erro médio de previsão (RMSE e MAE) e explicou a maior proporção da variância no consumo de energia (R²), indicando que é o modelo que melhor se ajusta aos dados e prevê o consumo de forma mais precisa.")
else:
     print("A análise das métricas de avaliação mostra que diferentes modelos podem ter pontos fortes em diferentes métricas. No entanto, o modelo Random Forest Regressor consistentemente apresentou melhores resultados em RMSE, R² e MAE, indicando que é o modelo mais robusto para prever o consumo de energia neste dataset.")

Comparação de Desempenho dos Modelos:
----------------------------------------
Modelo               | RMSE       | R²         | MAE       
----------------------------------------
Regressão Linear     | 92.4523    | 0.1459     | 53.4392   
Regressão de Árvore de Decisão | 90.7799    | 0.1765     | 38.1252   
Random Forest Regressor | 64.0201    | 0.5904     | 30.5115   
----------------------------------------

Discussão:
Para avaliar o desempenho dos modelos de regressão, utilizamos as seguintes métricas:
- RMSE (Root Mean Squared Error): Mede a raiz quadrada da média dos erros quadrados. Penaliza erros maiores e indica a magnitude típica dos erros de previsão na mesma unidade da variável alvo.
- R² (R-squared): Representa a proporção da variância na variável dependente que é previsível a partir das variáveis independentes. Um valor mais próximo de 1 indica que o modelo explica uma maior parte da variância dos dados.
- MAE (Mean Absolute Error): Mede a média dos erros absolutos. É men

# Exercício 2 - Classificação (Smart Grid Stability)

# Carregamento dos dados

In [ ]:
import pandas as pd

df_grid = pd.read_csv('/content/smart_grid_stability_augmented.csv')
display(df_grid.head())
display(df_grid.info())
display(df_grid['stabf'].value_counts())

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    60000 non-null  float64
 1   tau2    60000 non-null  float64
 2   tau3    60000 non-null  float64
 3   tau4    60000 non-null  float64
 4   p1      60000 non-null  float64
 5   p2      60000 non-null  float64
 6   p3      60000 non-null  float64
 7   p4      60000 non-null  float64
 8   g1      60000 non-null  float64
 9   g2      60000 non-null  float64
 10  g3      60000 non-null  float64
 11  g4      60000 non-null  float64
 12  stab    60000 non-null  float64
 13  stabf   60000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 6.4+ MB


None

stabf
unstable    38280
stable      21720
Name: count, dtype: int64

# Pré-processamento e processamento dos dados

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df_grid.drop(['stab', 'stabf'], axis=1)
y = df_grid['stabf']

numerical_features = X.columns.tolist()

scaler = StandardScaler()

X[numerical_features] = scaler.fit_transform(X[numerical_features])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

tau1      tau2      tau3      tau4        p1        p2        p3  \
48572  1.129543  1.726514  1.059525  0.687641  1.257212 -1.493692 -1.040221   
38696  1.693901 -0.011534 -1.531814 -1.225373 -1.190822  1.298100  1.629712   
13611  0.931985 -1.394627 -0.591586  0.626323 -0.957030  1.087540 -0.896396   
35213  0.914392 -1.569813  1.595629  0.763249  0.809421 -1.477911  1.086703   
31766 -1.651294 -0.995641  0.089400  0.948869  1.887863 -0.707468 -0.963545   

             p4        g1        g2        g3        g4  
48572  0.350199  1.530448  1.616867 -0.244457  0.848759  
38696 -0.859414 -0.452117 -0.431227 -0.689044  0.501455  
13611  1.471169 -0.601180  1.110587 -0.884969 -1.625643  
35213 -1.014716 -0.876993 -1.270139 -0.833456 -1.243011  
31766 -1.608110 -0.607596 -0.716800 -0.264250  1.662188

tau1      tau2      tau3      tau4        p1        p2        p3  \
12628  1.134798  1.584384  1.170590  0.574695  1.146614  0.379478 -0.800416   
37730  0.624532 -0.699571  0.171724 -0.490495  1.201217 -0.827452 -0.009321   
39991 -1.550100  1.704672 -0.862036  1.340630 -0.119353  0.338277 -0.464350   
8525   0.628952 -1.239991 -1.658152 -1.577947 -0.143617  0.566722 -1.347483   
8279  -1.517575  1.595771  1.178771  0.427239  0.560153 -1.464042  0.347951   

             p4        g1        g2        g3        g4  
12628 -1.570675  1.445146 -0.975494  0.151558 -1.572639  
37730 -1.249681 -1.157496  1.731100  1.461928  0.403829  
39991  0.333382  0.702521  1.567668  0.609036 -0.123590  
8525   1.030216  0.393212 -1.151572  1.722910  0.920820  
8279   0.143133  1.305695  1.211446 -1.461168  0.007536

48572    unstable
38696      stable
13611      stable
35213      stable
31766    unstable
Name: stabf, dtype: object

12628    unstable
37730    unstable
39991    unstable
8525       stable
8279     unstable
Name: stabf, dtype: object

# Treinamento dos modelos de classificação

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

dt_model = DecisionTreeClassifier(random_state=42)
knn_model = KNeighborsClassifier()
lr_model = LogisticRegression(random_state=42)

dt_model.fit(X_train, y_train)
knn_model.fit(X_train, y_train)
lr_model.fit(X_train, y_train)

LogisticRegression(random_state=42)

# Avaliação dos modelos de classificação

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

y_pred_dt = dt_model.predict(X_test)
y_pred_knn = knn_model.predict(X_test)
y_pred_lr = lr_model.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt, pos_label='unstable')

print("Decision Tree Model:")
print(f"Accuracy: {accuracy_dt:.4f}")
print("Confusion Matrix:")
print(conf_matrix_dt)
print(f"F1-score (unstable): {f1_dt:.4f}")
print("-" * 30)

accuracy_knn = accuracy_score(y_test, y_pred_knn)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn, pos_label='unstable')

print("K-Nearest Neighbors Model:")
print(f"Accuracy: {accuracy_knn:.4f}")
print("Confusion Matrix:")
print(conf_matrix_knn)
print(f"F1-score (unstable): {f1_knn:.4f}")
print("-" * 30)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
conf_matrix_lr = confusion_matrix(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr, pos_label='unstable')

print("Logistic Regression Model:")
print(f"Accuracy: {accuracy_lr:.4f}")
print("Confusion Matrix:")
print(conf_matrix_lr)
print(f"F1-score (unstable): {f1_lr:.4f}")
print("-" * 30)

Decision Tree Model:
Accuracy: 0.8958
Confusion Matrix:
[[3705  617]
 [ 634 7044]]
F1-score (unstable): 0.9184
------------------------------
K-Nearest Neighbors Model:
Accuracy: 0.8872
Confusion Matrix:
[[3421  901]
 [ 453 7225]]
F1-score (unstable): 0.9143
------------------------------
Logistic Regression Model:
Accuracy: 0.8102
Confusion Matrix:
[[3004 1318]
 [ 960 6718]]
F1-score (unstable): 0.8550
------------------------------


# Comparação e Discussão dos Resultados

In [ ]:
import pandas as pd

metrics_data = {'Model': ['Decision Tree', 'K-Nearest Neighbors', 'Logistic Regression'],
                'Accuracy': [accuracy_dt, accuracy_knn, accuracy_lr],
                'F1-score (unstable)': [f1_dt, f1_knn, f1_lr]}
df_metrics = pd.DataFrame(metrics_data)

display(df_metrics)

print("\nDiscussão:")
print("-" * 30)
print("Análise da Acurácia:")
print(f"- Acurácia mede a proporção de previsões corretas. Quanto maior, melhor.")
print(f"  - Decision Tree: {accuracy_dt:.4f}")
print(f"  - K-Nearest Neighbors: {accuracy_knn:.4f}")
print(f"  - Logistic Regression: {accuracy_lr:.4f}")

print("\nAnálise do F1-score (unstable):")
print(f"- O F1-score é a média harmônica da precisão e recall. É útil quando há um desequilíbrio nas classes.")
print(f"  - Decision Tree: {f1_dt:.4f}")
print(f"  - K-Nearest Neighbors: {f1_knn:.4f}")
print(f"  - Logistic Regression: {f1_lr:.4f}")

print("\nAnálise das Matrizes de Confusão:")
print("- Matriz de Confusão da Árvore de Decisão:")
print(conf_matrix_dt)
print("  - Verdadeiros Positivos (Unstable corretamente previstos):", conf_matrix_dt[1, 1])
print("  - Falsos Negativos (Unstable incorretamente previstos como Stable):", conf_matrix_dt[1, 0])
print("  - Falsos Positivos (Stable incorretamente previstos como Unstable):", conf_matrix_dt[0, 1])
print("  - Verdadeiros Negativos (Stable corretamente previstos):", conf_matrix_dt[0, 0])


print("\n- Matriz de Confusão do K-Nearest Neighbors:")
print(conf_matrix_knn)
print("  - Verdadeiros Positivos (Unstable corretamente previstos):", conf_matrix_knn[1, 1])
print("  - Falsos Negativos (Unstable incorretamente previstos como Stable):", conf_matrix_knn[1, 0])
print("  - Falsos Positivos (Stable incorretamente previstos como Unstable):", conf_matrix_knn[0, 1])
print("  - Verdadeiros Negativos (Stable corretamente previstos):", conf_matrix_knn[0, 0])

print("\n- Matriz de Confusão da Regressão Logística:")
print(conf_matrix_lr)
print("  - Verdadeiros Positivos (Unstable corretamente previstos):", conf_matrix_lr[1, 1])
print("  - Falsos Negativos (Unstable incorretamente previstos como Stable):", conf_matrix_lr[1, 0])
print("  - Falsos Positivos (Stable incorretamente previstos como Unstable):", conf_matrix_lr[0, 1])
print("  - Verdadeiros Negativos (Stable corretamente previstos):", conf_matrix_lr[0, 0])


print("\nConclusão:")
print("-" * 30)

best_accuracy_model = df_metrics.loc[df_metrics['Accuracy'].idxmax()]
best_f1_model = df_metrics.loc[df_metrics['F1-score (unstable)'].idxmax()]

print(f"Com base na Acurácia, o melhor modelo é: {best_accuracy_model['Model']} ({best_accuracy_model['Accuracy']:.4f})")
print(f"Com base no F1-score (unstable), o melhor modelo é: {best_f1_model['Model']} ({best_f1_model['F1-score (unstable)']:.4f})")

print("\nConsiderando a importância de detectar a instabilidade (classe 'unstable'), o F1-score é uma métrica crucial.")
print(f"O modelo com o maior F1-score para a classe 'unstable' foi o {best_f1_model['Model']}.")
print("Isso indica que ele alcançou um bom equilíbrio entre precisão e recall na identificação de casos instáveis, sendo mais confiável para essa tarefa específica.")

if best_accuracy_model['Model'] == best_f1_model['Model']:
    print(f"\nEm resumo, o modelo {best_accuracy_model['Model']} apresentou o melhor desempenho geral e é o mais recomendado para classificar a estabilidade da rede elétrica neste dataset.")
else:
     print(f"\nEmbora o modelo {best_accuracy_model['Model']} tenha a maior acurácia geral, o modelo {best_f1_model['Model']} é mais confiável para detectar a instabilidade (classe 'unstable') devido ao seu maior F1-score.")

Model  Accuracy  F1-score (unstable)
0        Decision Tree  0.895750             0.918443
1  K-Nearest Neighbors  0.887167             0.914325
2  Logistic Regression  0.810167             0.855034


Discussão:
------------------------------
Análise da Acurácia:
- Acurácia mede a proporção de previsões corretas. Quanto maior, melhor.
  - Decision Tree: 0.8958
  - K-Nearest Neighbors: 0.8872
  - Logistic Regression: 0.8102

Análise do F1-score (unstable):
- O F1-score é a média harmônica da precisão e recall. É útil quando há um desequilíbrio nas classes.
  - Decision Tree: 0.9184
  - K-Nearest Neighbors: 0.9143
  - Logistic Regression: 0.8550

Análise das Matrizes de Confusão:
- Matriz de Confusão da Árvore de Decisão:
[[3705  617]
 [ 634 7044]]
  - Verdadeiros Positivos (Unstable corretamente previstos): 7044
  - Falsos Negativos (Unstable incorretamente previstos como Stable): 634
  - Falsos Positivos (Stable incorretamente previstos como Unstable): 617
  - Verdadeiros Negativos (Stable corretamente previstos): 3705

- Matriz de Confusão do K-Nearest Neighbors:
[[3421  901]
 [ 453 7225]]
  - Verdadeiros Positivos (Unstable corretamente previstos): 7225
  - Falsos Negativos (Unst

# PARTE 2

# Exercício 1 - Classificação (Solar)

In [ ]:
import pandas as pd

df = pd.read_csv('/content/SolarPrediction.csv')
display(df.head())
display(df.info())

UNIXTime                   Data      Time  Radiation  Temperature  \
0  1475229326  9/29/2016 12:00:00 AM  23:55:26       1.21           48   
1  1475229023  9/29/2016 12:00:00 AM  23:50:23       1.21           48   
2  1475228726  9/29/2016 12:00:00 AM  23:45:26       1.23           48   
3  1475228421  9/29/2016 12:00:00 AM  23:40:21       1.21           48   
4  1475228124  9/29/2016 12:00:00 AM  23:35:24       1.17           48   

   Pressure  Humidity  WindDirection(Degrees)  Speed TimeSunRise TimeSunSet  
0     30.46        59                  177.39   5.62    06:13:00   18:13:00  
1     30.46        58                  176.78   3.37    06:13:00   18:13:00  
2     30.46        57                  158.75   3.37    06:13:00   18:13:00  
3     30.46        60                  137.71   3.37    06:13:00   18:13:00  
4     30.46        62                  104.95   5.62    06:13:00   18:13:00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32686 entries, 0 to 32685
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   UNIXTime                32686 non-null  int64  
 1   Data                    32686 non-null  object 
 2   Time                    32686 non-null  object 
 3   Radiation               32686 non-null  float64
 4   Temperature             32686 non-null  int64  
 5   Pressure                32686 non-null  float64
 6   Humidity                32686 non-null  int64  
 7   WindDirection(Degrees)  32686 non-null  float64
 8   Speed                   32686 non-null  float64
 9   TimeSunRise             32686 non-null  object 
 10  TimeSunSet              32686 non-null  object 
dtypes: float64(4), int64(3), object(4)
memory usage: 2.7+ MB


None

In [ ]:
radiation_median = df['Radiation'].median()
df['Radiation_Class'] = df['Radiation'].apply(lambda x: 'High Radiation' if x >= radiation_median else 'Low Radiation')
display(df[['Radiation', 'Radiation_Class']].head())
display(df['Radiation_Class'].value_counts())

Radiation Radiation_Class
0       1.21   Low Radiation
1       1.21   Low Radiation
2       1.23   Low Radiation
3       1.21   Low Radiation
4       1.17   Low Radiation

Radiation_Class
High Radiation    16344
Low Radiation     16342
Name: count, dtype: int64

# Processamento de dados



In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(['Radiation', 'Radiation_Class', 'UNIXTime', 'Data', 'Time', 'TimeSunRise', 'TimeSunSet'], axis=1)

y = df['Radiation_Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

continuous_features = ['Temperature', 'Pressure', 'Humidity', 'WindDirection(Degrees)', 'Speed']

scaler = StandardScaler()

X_train[continuous_features] = scaler.fit_transform(X_train[continuous_features])
X_test[continuous_features] = scaler.transform(X_test[continuous_features])

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

Temperature  Pressure  Humidity  WindDirection(Degrees)     Speed
28075     0.950194  1.230683  0.729345               -1.630214 -0.502207
23227     2.077442  0.865431 -1.655714               -0.603252  0.797419
16671    -1.143267  0.500179 -1.155621                2.340200 -1.478370
18527    -0.177055  0.317552  1.037095               -0.663718 -0.828557
2165      0.145016 -0.412952 -1.578777                0.309523  0.471069

Temperature  Pressure  Humidity  WindDirection(Degrees)     Speed
22107     1.272264  0.865431 -1.194090                2.040158 -0.828557
3780      1.272264  1.048057  0.306189               -1.268140  0.147606
13651    -0.660161 -0.595578  0.113846                0.847094 -0.178744
30473    -0.982232 -0.412952  0.883220                0.401547 -0.502207
9084     -0.982232 -0.412952 -1.578777                0.392634  0.147606

28075    High Radiation
23227    High Radiation
16671    High Radiation
18527     Low Radiation
2165     High Radiation
Name: Radiation_Class, dtype: object

22107    High Radiation
3780     High Radiation
13651     Low Radiation
30473    High Radiation
9084      Low Radiation
Name: Radiation_Class, dtype: object

# Treinamento do modelo



In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

dt_model = DecisionTreeClassifier(random_state=42)
rf_model = RandomForestClassifier(random_state=42)
svm_model = SVC(random_state=42)

dt_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)
svm_model.fit(X_train, y_train)

SVC(random_state=42)

# Avaliação do modelo


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

y_pred_dt = dt_model.predict(X_test)
y_pred_rf = rf_model.predict(X_test)
y_pred_svm = svm_model.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)
print("Decision Tree Model:")
print(f"Accuracy: {accuracy_dt:.4f}")
print("Confusion Matrix:")
print(conf_matrix_dt)
print("-" * 30)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
print("Random Forest Model:")
print(f"Accuracy: {accuracy_rf:.4f}")
print("Confusion Matrix:")
print(conf_matrix_rf)
print("-" * 30)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)
print("SVM Model:")
print(f"Accuracy: {accuracy_svm:.4f}")
print("Confusion Matrix:")
print(conf_matrix_svm)

Decision Tree Model:
Accuracy: 0.8333
Confusion Matrix:
[[4071  786]
 [ 849 4100]]
------------------------------
Random Forest Model:
Accuracy: 0.8777
Confusion Matrix:
[[4071  786]
 [ 413 4536]]
------------------------------
SVM Model:
Accuracy: 0.8295
Confusion Matrix:
[[3497 1360]
 [ 312 4637]]


# Comparação dos modelos



In [ ]:
print("Comparação de Desempenho dos Modelos:")
print("-" * 30)
print(f"Acurácia da Árvore de Decisão: {accuracy_dt:.4f}")
print(f"Acurácia do Random Forest: {accuracy_rf:.4f}")
print(f"Acurácia do SVM: {accuracy_svm:.4f}")
print("-" * 30)

print("\nAnálise da Matriz de Confusão:")
print("-" * 30)

print("Matriz de Confusão da Árvore de Decisão:")
print(conf_matrix_dt)
print("Interpretação:")
print(f"  Verdadeiros Positivos (Alta Radiação corretamente prevista): {conf_matrix_dt[1, 1]}")
print(f"  Verdadeiros Negativos (Baixa Radiação corretamente prevista): {conf_matrix_dt[0, 0]}")
print(f"  Falsos Positivos (Alta Radiação incorretamente prevista): {conf_matrix_dt[0, 1]}")
print(f"  Falsos Negativos (Baixa Radiação incorretamente prevista): {conf_matrix_dt[1, 0]}")
print("-" * 30)

print("Matriz de Confusão do Random Forest:")
print(conf_matrix_rf)
print("Interpretação:")
print(f"  Verdadeiros Positivos (Alta Radiação corretamente prevista): {conf_matrix_rf[1, 1]}")
print(f"  Verdadeiros Negativos (Baixa Radiação corretamente prevista): {conf_matrix_rf[0, 0]}")
print(f"  Falsos Positivos (Alta Radiação incorretamente prevista): {conf_matrix_rf[0, 1]}")
print(f"  Falsos Negativos (Baixa Radiação incorretamente prevista): {conf_matrix_rf[1, 0]}")
print("-" * 30)

print("Matriz de Confusão do SVM:")
print(conf_matrix_svm)
print("Interpretação:")
print(f"  Verdadeiros Positivos (Alta Radiação corretamente prevista): {conf_matrix_svm[1, 1]}")
print(f"  Verdadeiros Negativos (Baixa Radiação corretamente prevista): {conf_matrix_svm[0, 0]}")
print(f"  Falsos Positivos (Alta Radiação incorretamente prevista): {conf_matrix_svm[0, 1]}")
print(f"  Falsos Negativos (Baixa Radiação incorretamente prevista): {conf_matrix_svm[1, 0]}")
print("-" * 30)

print("\nConclusão:")
if accuracy_rf > accuracy_dt and accuracy_rf > accuracy_svm:
    print("O modelo Random Forest teve o melhor desempenho com a maior acurácia.")
    print("Ele também tem um bom equilíbrio entre verdadeiros positivos e verdadeiros negativos, e relativamente menos falsos negativos em comparação com a Árvore de Decisão.")
elif accuracy_dt > accuracy_svm:
    print("O modelo de Árvore de Decisão teve o melhor desempenho com a maior acurácia.")
    print("Analise sua matriz de confusão para pontos fortes e fracos específicos.")
else:
    print("O modelo SVM teve o melhor desempenho com a maior acurácia.")
    print("Analise sua matriz de confusão para pontos fortes e fracos específicos.")

Comparação de Desempenho dos Modelos:
------------------------------
Acurácia da Árvore de Decisão: 0.8333
Acurácia do Random Forest: 0.8777
Acurácia do SVM: 0.8295
------------------------------

Análise da Matriz de Confusão:
------------------------------
Matriz de Confusão da Árvore de Decisão:
[[4071  786]
 [ 849 4100]]
Interpretação:
  Verdadeiros Positivos (Alta Radiação corretamente prevista): 4100
  Verdadeiros Negativos (Baixa Radiação corretamente prevista): 4071
  Falsos Positivos (Alta Radiação incorretamente prevista): 786
  Falsos Negativos (Baixa Radiação incorretamente prevista): 849
------------------------------
Matriz de Confusão do Random Forest:
[[4071  786]
 [ 413 4536]]
Interpretação:
  Verdadeiros Positivos (Alta Radiação corretamente prevista): 4536
  Verdadeiros Negativos (Baixa Radiação corretamente prevista): 4071
  Falsos Positivos (Alta Radiação incorretamente prevista): 786
  Falsos Negativos (Baixa Radiação incorretamente prevista): 413
----------------

# Exercício 2 - Regressão (Eólica)

In [ ]:
import pandas as pd

df = pd.read_csv('T1.csv')
display(df.head())
display(df.info())

Date/Time  LV ActivePower (kW)  Wind Speed (m/s)  \
0  01 01 2018 00:00           380.047791          5.311336   
1  01 01 2018 00:10           453.769196          5.672167   
2  01 01 2018 00:20           306.376587          5.216037   
3  01 01 2018 00:30           419.645905          5.659674   
4  01 01 2018 00:40           380.650696          5.577941   

   Theoretical_Power_Curve (KWh)  Wind Direction (°)  
0                     416.328908          259.994904  
1                     519.917511          268.641113  
2                     390.900016          272.564789  
3                     516.127569          271.258087  
4                     491.702972          265.674286

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50530 entries, 0 to 50529
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Date/Time                      50530 non-null  object 
 1   LV ActivePower (kW)            50530 non-null  float64
 2   Wind Speed (m/s)               50530 non-null  float64
 3   Theoretical_Power_Curve (KWh)  50530 non-null  float64
 4   Wind Direction (°)             50530 non-null  float64
dtypes: float64(4), object(1)
memory usage: 1.9+ MB


None

# Processamento dos dados

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(['Date/Time', 'LV ActivePower (kW)'], axis=1)

y = df['LV ActivePower (kW)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

continuous_features = ['Wind Speed (m/s)', 'Theoretical_Power_Curve (KWh)', 'Wind Direction (°)']

scaler = StandardScaler()

X_train[continuous_features] = scaler.fit_transform(X_train[continuous_features])
X_test[continuous_features] = scaler.transform(X_test[continuous_features])

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  Wind Direction (°)
13791         -1.125253                      -1.091661            0.600542
46267         -0.614677                      -0.852852           -0.007299
42105          1.220175                       1.531968            0.937698
21123         -0.111835                      -0.318188           -0.744266
11823         -0.304133                      -0.564102           -0.869168

Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  Wind Direction (°)
8057           0.958781                       1.429847            0.692928
8059           0.655204                       1.091157            0.716680
50250         -0.268498                      -0.522707           -1.013826
14774          0.090465                       0.005713           -0.796969
49374         -0.392151                      -0.657970            1.659031

13791       0.000000
46267     292.170105
42105    3387.934082
21123    1082.370972
11823     550.262329
Name: LV ActivePower (kW), dtype: float64

8057     3348.910889
8059     2647.506104
50250       0.000000
14774    1334.573975
49374     533.002808
Name: LV ActivePower (kW), dtype: float64

In [ ]:
continuous_features = ['Wind Speed (m/s)', 'Theoretical_Power_Curve (KWh)', 'Wind Direction (°)']

scaler = StandardScaler()

X_train[continuous_features] = scaler.fit_transform(X_train[continuous_features])
X_test[continuous_features] = scaler.transform(X_test[continuous_features])

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  Wind Direction (°)
13791         -1.125253                      -1.091661            0.600542
46267         -0.614677                      -0.852852           -0.007299
42105          1.220175                       1.531968            0.937698
21123         -0.111835                      -0.318188           -0.744266
11823         -0.304133                      -0.564102           -0.869168

Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  Wind Direction (°)
8057           0.958781                       1.429847            0.692928
8059           0.655204                       1.091157            0.716680
50250         -0.268498                      -0.522707           -1.013826
14774          0.090465                       0.005713           -0.796969
49374         -0.392151                      -0.657970            1.659031

13791       0.000000
46267     292.170105
42105    3387.934082
21123    1082.370972
11823     550.262329
Name: LV ActivePower (kW), dtype: float64

8057     3348.910889
8059     2647.506104
50250       0.000000
14774    1334.573975
49374     533.002808
Name: LV ActivePower (kW), dtype: float64

In [ ]:
print(df.columns)

Index(['Date/Time', 'LV ActivePower (kW)', 'Wind Speed (m/s)',
       'Theoretical_Power_Curve (KWh)', 'Wind Direction (°)'],
      dtype='object')


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(['Date/Time', 'LV ActivePower (kW)'], axis=1)

y = df['LV ActivePower (kW)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

continuous_features = ['Wind Speed (m/s)', 'Theoretical_Power_Curve (KWh)', 'Wind Direction (°)']

scaler = StandardScaler()

X_train[continuous_features] = scaler.fit_transform(X_train[continuous_features])
X_test[continuous_features] = scaler.transform(X_test[continuous_features])

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  Wind Direction (°)
13791         -1.125253                      -1.091661            0.600542
46267         -0.614677                      -0.852852           -0.007299
42105          1.220175                       1.531968            0.937698
21123         -0.111835                      -0.318188           -0.744266
11823         -0.304133                      -0.564102           -0.869168

Wind Speed (m/s)  Theoretical_Power_Curve (KWh)  Wind Direction (°)
8057           0.958781                       1.429847            0.692928
8059           0.655204                       1.091157            0.716680
50250         -0.268498                      -0.522707           -1.013826
14774          0.090465                       0.005713           -0.796969
49374         -0.392151                      -0.657970            1.659031

13791       0.000000
46267     292.170105
42105    3387.934082
21123    1082.370972
11823     550.262329
Name: LV ActivePower (kW), dtype: float64

8057     3348.910889
8059     2647.506104
50250       0.000000
14774    1334.573975
49374     533.002808
Name: LV ActivePower (kW), dtype: float64

# Treinamento do modelo





In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

lr_model = LinearRegression()
dt_model = DecisionTreeRegressor(random_state=42)
rf_model = RandomForestRegressor(random_state=42)

lr_model.fit(X_train, y_train)
dt_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

# Avaliação do modelo


In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

y_pred_lr = lr_model.predict(X_test)
y_pred_dt = dt_model.predict(X_test)
y_pred_rf = rf_model.predict(X_test)

rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)

rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
r2_dt = r2_score(y_test, y_pred_dt)

rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print("Model Evaluation Results:")
print("-" * 30)
print(f"Linear Regression:")
print(f"  RMSE: {rmse_lr:.4f}")
print(f"  R²: {r2_lr:.4f}")
print("-" * 30)
print(f"Decision Tree Regressor:")
print(f"  RMSE: {rmse_dt:.4f}")
print(f"  R²: {r2_dt:.4f}")
print("-" * 30)
print(f"Random Forest Regressor:")
print(f"  RMSE: {rmse_rf:.4f}")
print(f"  R²: {r2_rf:.4f}")
print("-" * 30)

Model Evaluation Results:
------------------------------
Linear Regression:
  RMSE: 411.7100
  R²: 0.9007
------------------------------
Decision Tree Regressor:
  RMSE: 538.7904
  R²: 0.8299
------------------------------
Random Forest Regressor:
  RMSE: 412.8221
  R²: 0.9001
------------------------------


# Comparação dos modelos




In [ ]:
print("Comparação de Desempenho dos Modelos:")
print("-" * 40)
print(f"{'Modelo':<20} | {'RMSE':<10} | {'R²':<10}")
print("-" * 40)
print(f"{'Regressão Linear':<20} | {rmse_lr:<10.4f} | {r2_lr:<10.4f}")
print(f"{'Regressão de Árvore de Decisão':<20} | {rmse_dt:<10.4f} | {r2_dt:<10.4f}")
print(f"{'Random Forest Regressor':<20} | {rmse_rf:<10.4f} | {r2_rf:<10.4f}")
print("-" * 40)

print("\nInterpretação:")
print("RMSE (Root Mean Squared Error) mede a magnitude média dos erros entre os valores previstos e reais. Um RMSE menor indica melhor desempenho do modelo.")
print("R² (R-squared) representa a proporção da variância na variável dependente que é previsível a partir das variáveis independentes. Um R² maior indica um melhor ajuste do modelo aos dados.")

print("\nCom base nos resultados:")
if rmse_lr < rmse_dt and rmse_lr < rmse_rf:
    print("- A Regressão Linear tem o menor RMSE, sugerindo que tem os menores erros médios de previsão.")
elif rmse_dt < rmse_rf:
    print("- A Regressão de Árvore de Decisão tem o menor RMSE.")
else:
    print("- O Random Forest Regressor tem o menor RMSE, indicando que é o modelo com melhor desempenho em termos de precisão de previsão em média.")

if r2_lr > r2_dt and r2_lr > r2_rf:
    print("- A Regressão Linear tem o maior R², o que significa que explica a maior parte da variância na variável alvo.")
elif r2_dt > r2_rf:
    print("- A Regressão de Árvore de Decisão tem o maior R².")
else:
    print("- O Random Forest Regressor tem o maior R², indicando que fornece o melhor ajuste aos dados e explica a maior parte da variância na geração de energia.")

print("\nConclusão Geral:")
if rmse_rf < rmse_dt and rmse_rf < rmse_lr and r2_rf > r2_dt and r2_rf > r2_lr:
    print("O Random Forest Regressor parece ser o modelo com melhor desempenho com base nos menores valores de RMSE e maiores valores de R².")
elif rmse_lr < rmse_dt and rmse_lr < rmse_rf and r2_lr > r2_dt and r2_lr > r2_rf:
     print("A Regressão Linear parece ser o modelo com melhor desempenho com base nos menores valores de RMSE e maiores valores de R².")
elif rmse_dt < rmse_rf and rmse_dt < rmse_lr and r2_dt > r2_rf and r2_dt > r2_lr:
    print("A Regressão de Árvore de Decisão parece ser o modelo com melhor desempenho com base nos menores valores de RMSE e maiores valores de R².")
else:
    print("Analise as compensações específicas entre RMSE e R² para cada modelo para tomar uma decisão final.")

Comparação de Desempenho dos Modelos:
----------------------------------------
Modelo               | RMSE       | R²        
----------------------------------------
Regressão Linear     | 411.7100   | 0.9007    
Regressão de Árvore de Decisão | 538.7904   | 0.8299    
Random Forest Regressor | 412.8221   | 0.9001    
----------------------------------------

Interpretação:
RMSE (Root Mean Squared Error) mede a magnitude média dos erros entre os valores previstos e reais. Um RMSE menor indica melhor desempenho do modelo.
R² (R-squared) representa a proporção da variância na variável dependente que é previsível a partir das variáveis independentes. Um R² maior indica um melhor ajuste do modelo aos dados.

Com base nos resultados:
- A Regressão Linear tem o menor RMSE, sugerindo que tem os menores erros médios de previsão.
- A Regressão Linear tem o maior R², o que significa que explica a maior parte da variância na variável alvo.

Conclusão Geral:
A Regressão Linear parece ser o modelo